### ISSUE TITLE
Logout dan login mashi user yang sama

### ISSUE THREAD

**Issue by AdeSupriyadi** [pudyasto/rbac#2]
sy coba aplikasinya, namun ada kendala sbb:
I -
1. login dengan user A
2. user A logout
3. Login dengan user B

masuk dashboard tetap user A

II-
jika sudah login masuk dashboard, tekan back, masuk kembali ke login page

**Comment by pudyasto** [comment]
Terima kasih untuk informasinya, untuk saat ini memang masih banyak yg perlu dikembangkan. 
Anda juga bisa berpartisipasi untuk mengembangan sistem ini.
